name: tests
run-name: Tests
on: [pull_request]
jobs:
  postman-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
      - run: gradle bootJar
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "compose.yaml"
      - uses: gacts/install-hurl@v1
      - run: hurl tests/*.hurl
